### PR TITLE
[Network] #364: Change relay methods prefix from "iridium" to "irn"

### PR DESCRIPTION
**Pull request by MisterVants**
#closes 364

Self-explanatory

### CODE REVIEW

**Review by flypaper0 — APPROVED** [review]

**Comment by llbartekll** [comment]
let's change relay protocol options for irn as well. so uri do not contain legacy naming

**Review by llbartekll — CHANGES_REQUESTED** [review]
let's change relay protocol options for irn as well. so uri do not contain legacy naming

**Review by llbartekll — COMMENTED** [review]
I am afraid that changing storage identifier will break existing integrations. Can you manually test it?

**Comment by MisterVants** [comment]
I think we can just leave as it is, it's well isolated and won't affect the protocol

**Review by llbartekll — APPROVED** [review]

**Pull request merged**
