### PR TITLE
Add Mixpanel

### PR DESCRIPTION
**Pull request by llbartekll**
# Description

Resolves # (issue)

## Due Dilligence

* [ ] Breaking change
* [ ] Requires a documentation update

### CODE REVIEW

**Review by flypaper0 — APPROVED** [review]
nice job

**Comment by chrismaddern** [comment]
Strongly, **Strongly** recommend updating the changelog to clarify:

> Added Mixpanel **TO THE EXAMPLE APP**

I was about to fork the repo and remove it when I read your notes 🤣

**Comment by llbartekll** [comment]
@chrismaddern, we use it only for our internal testing in the sample app.
you can safely build the app for yourself and you won't be logging.
sdk does not have that dependency at all

**Comment by chrismaddern** [comment]
Thanks! Yep -- figured that out by looking through the code, but had a heart attack when I saw it 🤣 🤣 🤣 🤣

**Pull request merged**
