### PR TITLE
[Core] CAIP-10 regex fixed

### PR DESCRIPTION
**Pull request by flypaper0**
# Description
CAIP-10 Regex updated with https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-10.md#syntax

Resolves https://github.com/WalletConnect/WalletConnectSwiftV2/pull/761

## Due Dilligence

* [ ] Breaking change
* [ ] Requires a documentation update

### CODE REVIEW

**Comment by nerzh** [comment]
Hello. I recreated my pull request as you asked #765 . Why did you create the same as #761 ?

**Comment by nerzh** [comment]
@flypaper0 ok, let me download the project again and re-upload with test fixes ?

**Comment by nerzh** [comment]
although I changed my mind 🙄, do as you wish, have a nice day, bye

**Comment by flypaper0** [comment]
Ok, I'll merge this. Normally we are doing branch from fresh develop, doing commits, and PR in develop. I think the reason of bad branch in your PR, that you initially created branch from main, and after changed destination branch to develop. Thanks for contribution 🙏

**Pull request merged**
