### PR TITLE
[Infra] Cocoapods support #258

### LINKED ISSUE #258: Cocoapods available
for now, is this package available on cocoapods?

### PR DESCRIPTION
**Pull request by flypaper0**
# Description
- Podspec file
- File duplicates removed
- *Imports.swift files for @_exported imports

Resolves #258 (issue)

## How Has This Been Tested?
Cocoapods integration can be tested on `v1.0.5-rc` tag
``` ruby
pod 'WalletConnectSwiftV2', :git => 'https://github.com/WalletConnect/WalletConnectSwiftV2.git', :tag => 'v1.0.5-rc'
```

## Due Dilligence

* [ ] Breaking change
* [x] Requires a documentation update

### CODE REVIEW

**Comment by smallerboy** [comment]
it's great !

**Comment by smallerboy** [comment]
some file miss, just like Sign and Auth Pakcage

**Review by llbartekll — APPROVED** [review]

**Comment by flypaper0** [comment]
> some file miss, just like Sign and Auth Package

Good catch, fixed. There was wrong source paths. 

Released new tag: 
``` ruby
pod 'WalletConnectSwiftV2', :git => 'https://github.com/WalletConnect/WalletConnectSwiftV2.git', :tag => 'v1.0.5-rc3'
```

Regarding Auth. Auth is available buy downloading subspec.
``` ruby
pod 'WalletConnectSwiftV2/WalletConnectAuth', :git => 'https://github.com/WalletConnect/WalletConnectSwiftV2.git', :tag => 'v1.0.5-rc3'
```

**Comment by syp1027825441** [comment]
the demo can not use,by cocoapods version

**Comment by smallerboy** [comment]
> the demo can not use,by cocoapods version. Error Tips 'No such module 'WalletConnectSign''

maybe you can import walletConnectv2  replace 'WalletConnectSign'

**Pull request merged**
